# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'PAYG subscription(98510e54-4e62-4d79-8000-68ac56355c66)'
    appType: 'webAppLinux'
    appName: 'appjava-wa'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'JAVA|8-jre8'